app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from contacts.views import goto


urlpatterns = [
    path('', goto),
    path('admin/', admin.site.urls),
    path('contact-list/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/contacts/urls.py
from django.urls import path

from .views import ContactList, PersonView, AddPersonAddress, ModifyPersonAddress, AddPersonEmail, \
    ModifyPersonEmail, AddPersonPhone, ModifyPersonPhone, GroupsView, AddGroupView, ModifyGroupView, AddToGroupView, \
    RemoveFromGroupView, GroupView, SearchGroupView, DeleteContactView


app_name = 'contacts'

urlpatterns = [
                  path('', ContactList.as_view(), name='contact_list'),
                  path('contact/<int:id>/', PersonView.as_view(), name='contact'),
                  path('contact/remove/<int:id>/', DeleteContactView.as_view(), name='delete-contact'),
                  path('contact/<int:id>/new-address/', AddPersonAddress.as_view(), name='add-address'),
                  path('contact/<int:id>/modify-address/<int:address_id>/', ModifyPersonAddress.as_view(),
                       name='modify-address'),
                  path('contact/<int:id>/new-email/', AddPersonEmail.as_view(), name='add-email'),
                  path('contact/<int:id>/modify-email/<int:email_id>/', ModifyPersonEmail.as_view(),
                       name='modify-email'),
                  path('contact/<int:id>/new-phone/', AddPersonPhone.as_view(), name='add-phone'),
                  path('contact/<int:id>/modify-phone/<int:phone_id>/', ModifyPersonPhone.as_view(),
                       name='modify-phone'),

                  path('groups/', GroupsView.as_view(), name='groups'),
                  path('groups/add-group/', AddGroupView.as_view(), name='add-group'),
                  path('groups/add-to-group/<int:id>/', AddToGroupView.as_view(), name='add-to-group'),
                  path('groups/remove-from-group/', RemoveFromGroupView.as_view(), name='remove-from-group'),
                  path('groups/modify-group/<int:group_id>/', ModifyGroupView.as_view(), name='modify-group'),
                  path('groups/group/<int:id>/', GroupView.as_view(), name='group'),
                  path('groups/group/<int:id>/search/', SearchGroupView.as_view(), name='search'),

              ]

app/contacts/models.py
from django.db import models
from PIL import Image


PHONE_CHOICES = (
    (0, 'Mobile'),
    (1, 'Home'),
    (2, 'Work'),
    (3, 'Private'),
    (4, 'FAX'),
)

EMAIL_CHOICES = (
    (0, 'Mobile'),
    (1, 'Home'),
    (2, 'Private'),
)


class Person(models.Model):
    name = models.CharField(max_length=64)
    surname = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    photo = models.ImageField(upload_to='avatar', blank=True, default='default.png')

    def __str__(self):
        return f"{self.name} {self.surname}"

    def save(self):
        super().save()

        # todo rename saved files
        img = Image.open(self.photo.path)
        if img.height > 128 or img.width > 128:
            output_size = (128, 128)
            img.thumbnail(output_size)
            img.save(self.photo.path)

    @property
    def full_name(self):
        return f"{self.surname} {self.name}"


class Address(models.Model):
    city = models.CharField(max_length=128)
    street = models.CharField(max_length=128)
    home_no = models.CharField(max_length=64)
    apartment_no = models.CharField(max_length=64)
    zip_code = models.IntegerField(blank=True)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.city}, {self.street} street, " \
               f"{self.home_no}/{self.apartment_no}"


class Phone(models.Model):
    number = models.CharField(max_length=32)
    number_type = models.IntegerField(default=0, choices=PHONE_CHOICES)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.number} {self.number_type}"


class Email(models.Model):
    email = models.CharField(max_length=64)
    email_type = models.IntegerField(default=0, choices=EMAIL_CHOICES)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.email} {self.email_type}"


class Group(models.Model):
    name = models.CharField(max_length=128, unique=True)
    person = models.ManyToManyField(Person)

    def __str__(self):
        return self.name

app/contacts/forms.py
from django import forms
from django.forms.utils import ErrorList
from django.core.validators import FileExtensionValidator, EmailValidator, RegexValidator
from .models import Person, Email, Address, Group, Phone, PHONE_CHOICES, EMAIL_CHOICES


class PersonForm(forms.ModelForm):
    name = forms.CharField(label='Name')
    surname = forms.CharField(label='Last Name')
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': '5'}),
                                  label='Contact Description')
    photo = forms.ImageField(required=False, validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg'])],
                             label='Contact Photo',
                             help_text="Allowed extensions: jpg, png."
                             )

    class Meta:
        model = Person
        fields = ('name', 'surname', 'description', 'photo')


class ShortPersonForm(forms.ModelForm):
    name = forms.CharField(label='Name')
    surname = forms.CharField(label='Last Name')

    class Meta:
        model = Person
        fields = ('name', 'surname')


class EmailForm(forms.ModelForm):
    email = forms.EmailField(validators=[EmailValidator()], label='Email')
    email_type = forms.IntegerField(label='Email Type',
                                    widget=forms.Select(choices=EMAIL_CHOICES))

    class Meta:
        model = Email
        fields = ('email', 'email_type')


class PhoneForm(forms.ModelForm):
    number = forms.CharField(validators=[RegexValidator(r'^(\+\d{2})?(\d{9})$')],
                             label='Phone Number')
    number_type = forms.IntegerField(label='Phone Type',
                                     widget=forms.Select(choices=PHONE_CHOICES))

    class Meta:
        model = Phone
        fields = ('number', 'number_type')


class AddressForm(forms.ModelForm):
    city = forms.CharField(label='City')
    street = forms.CharField(label='Street')
    home_no = forms.CharField(label='Home Number')
    apartment_no = forms.CharField(label='Apartment Number')
    zip_code = forms.IntegerField(validators=[RegexValidator(r'^(\d{2})\-?(\d{3})$')],
                                  label='Zip Code')

    class Meta:
        model = Address
        fields = ('city', 'street', 'home_no', 'apartment_no', 'zip_code')


class GroupForm(forms.ModelForm):
    name = forms.CharField(label='', required=True)

    class Meta:
        model = Group
        fields = ('name',)


class SelectGroupForm(forms.Form):
    group = forms.ModelMultipleChoiceField(queryset=None, required=True, label="")

    def __init__(self, person, *args, **kwargs):
        super(SelectGroupForm, self).__init__(*args, **kwargs)
        self.fields['group'].queryset = Group.objects.all().exclude(person=person).order_by('name')

app/contacts/views.py
import os

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from contacts.forms import PersonForm, AddressForm, EmailForm, PhoneForm, GroupForm, SelectGroupForm, ShortPersonForm
from contacts.models import Person, Address, Email, Phone, Group


def goto(request):
    return redirect('contacts:contact_list')


class ContactList(View):
    def get(self, request):
        contacts = Person.objects.all().order_by('surname')
        form = ShortPersonForm()
        return render(request, 'contacts/contact_list.html', {'form': form, 'contacts': contacts})

    def post(self, request):

        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Contact has been created.')
            return redirect('contacts:contact_list')
        else:
            messages.error(request, 'While adding new contact an error has occurred.')
            return redirect('contacts:contact_list')


class DeleteContactView(View):
    def post(self, request, id):
        person = get_object_or_404(Person, pk=id)
        person.delete()
        messages.success(request, 'Contact deleted.')
        return redirect('contacts:contact_list')


class PersonView(View):
    def get(self, request, id):
        person = Person.objects.get(pk=id)
        return render(request, 'contacts/contact_details.html', {'contact': person,
                                                                 'form': PersonForm(instance=person),
                                                                 'group_form': GroupForm(),
                                                                 'join_group_form': SelectGroupForm(person=person),
                                                                 'person_groups': person.group_set.all(),
                                                                 'groups': Group.objects.all(),
                                                                 'addresses': person.address_set.all(),
                                                                 'emails': person.email_set.all(),
                                                                 'phones': person.phone_set.all(),
                                                                 })

    def post(self, request, id):
        person = Person.objects.get(pk=id)
        img_path = person.photo.path
        form = PersonForm(request.POST or None, request.FILES or None, instance=person)
        action = request.POST.get('action')
        if action is not None:
            if action == 'delete_address':
                object = Address.objects.get(pk=int(request.POST.get('id')))
            elif action == 'delete_email':
                object = Email.objects.get(pk=int(request.POST.get('id')))
            elif action == 'delete_phone':
                object = Phone.objects.get(pk=int(request.POST.get('id')))
            object.delete()
            return redirect('contacts:contact', id=id)

        if form.is_valid():
            if request.POST.get('photo-clean'):
                os.remove(img_path)
            else:
                form.photo = img_path
            form.save()
            messages.success(request, "Contact was updated")
            return redirect('contacts:contact', id=id)
        else:
            messages.warning(request, 'While updating contact an error has occurred.')
        return render(request, 'contacts/contact_details.html', {'contact': person, 'form': form})


class AddPersonAddress(View):
    def get(self, request, id):
        form = AddressForm()
        return render(request, 'contacts/address.html', {'form': form})

    def post(self, request, id):
        form = AddressForm(data=request.POST)
        if form.is_valid():
            person = Person.objects.get(pk=id)
            address = form.save(commit=False)
            address.person = person
            address.save()
            messages.success(request, "Address was added")
            return redirect('contacts:contact', id=id)
        else:
            messages.warning(request, 'While updating contact an error has occurred.')
        return redirect('contacts:contact', id=id)


class ModifyPersonAddress(View):

    def get(self, request, id, address_id):
        person = get_object_or_404(Person, pk=id)
        address = get_object_or_404(Address, pk=address_id)
        form = AddressForm(instance=address)
        return render(request, 'contacts/address.html', {'form': form})

    def post(self, request, id, address_id):
        address = get_object_or_404(Address, pk=address_id)
        form = AddressForm(data=request.POST, instance=address)
        if form.is_valid():
            form.save()
            messages.success(request, "Address was updated")
            return redirect('contacts:contact', id=id)
        else:
            messages.warning(request, 'While updating address an error has occurred.')
        return redirect('contacts:contact', id=id)


class AddPersonEmail(View):
    def get(self, request, id):
        return render(request, 'contacts/email.html', {'form': EmailForm()})

    def post(self, request, id):
        form = EmailForm(data=request.POST)
        if form.is_valid():
            person = Person.objects.get(pk=id)
            email = form.save(commit=False)
            email.person = person
            email.save()
            messages.success(request, "Email was added")
            return redirect('contacts:contact', id=id)
        else:
            messages.warning(request, 'While updating email an error has occurred.')
        return redirect('contacts:contact', id=id)


class ModifyPersonEmail(View):
    def get(self, request, id, email_id):
        email = get_object_or_404(Email, pk=email_id)
        form = EmailForm(instance=email)
        return render(request, 'contacts/email.html', {'form': form})

    def post(self, request, id, email_id):
        email = get_object_or_404(Email, pk=email_id)
        form = EmailForm(data=request.POST, instance=email)
        if form.is_valid():
            form.save()
            messages.success(request, "Email was updated")
            return redirect('contacts:contact', id=id)
        else:
            messages.warning(request, 'While updating email an error has occurred.')
        return redirect('contacts:contact', id=id)


class AddPersonPhone(View):
    def get(self, request, id):
        form = PhoneForm()
        return render(request, 'contacts/phone.html', {'form': form})

    def post(self, request, id):
        form = PhoneForm(data=request.POST)
        if form.is_valid():
            person = Person.objects.get(pk=id)
            phone = form.save(commit=False)
            phone.person = person
            phone.save()
            messages.success(request, "Phone was added")
            return redirect('contacts:contact', id=id)
        else:
            messages.warning(request, 'While updating phone an error has occurred.')
        return redirect('contacts:contact', id=id)


class ModifyPersonPhone(View):

    def get(self, request, id, phone_id):
        person = get_object_or_404(Person, pk=id)
        phone = get_object_or_404(Phone, pk=phone_id)
        form = PhoneForm(instance=phone)
        return render(request, 'contacts/phone.html', {'form': form})

    def post(self, request, id, phone_id):
        phone = get_object_or_404(Email, pk=phone_id)
        form = PhoneForm(data=request.POST, instance=phone)
        if form.is_valid():
            form.save()
            messages.success(request, "Phone was updated")
            return redirect('contacts:contact', id=id)
        else:
            messages.warning(request, 'While updating phone an error has occurred.')
        return redirect('contacts:contact', id=id)


class GroupsView(View):
    def get(self, request):
        return render(request, 'contacts/groups.html', {'groups': Group.objects.all().order_by('name')})

    def post(self, request):
        if request.POST.get('action') == 'delete':
            group = Group.objects.get(pk=int(request.POST.get('id')))
            # todo delete all relevent group markers in contacts
            group.delete()
            messages.success(request, 'Group was deleted.')
        return redirect('contacts:groups')


class GroupView(View):
    def get(self, request, id):
        group = get_object_or_404(Group, pk=id)
        contacts = group.person.all()
        return render(request, 'contacts/group_details.html', {'group': group, 'contacts': contacts})


class AddGroupView(View):
    def post(self, request):
        form = GroupForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Group was created.")
            return redirect('contacts:groups')
        else:
            messages.error(request, 'Can not create group.')
        return redirect('contacts:groups')


class ModifyGroupView(View):
    def get(self, request, group_id):
        form = GroupForm(instance=get_object_or_404(Group, pk=group_id))
        return render(request, 'contacts/group.html', {'form': form})

    def post(self, request, group_id):
        form = GroupForm(instance=get_object_or_404(Group, pk=group_id), data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f"Group name was renamed.")
            return redirect('contacts:groups')
        form.add_error('name', 'Please provide different name.')
        messages.warning(request, 'An error has occurred.')
        render(request, 'contacts/group.html', {'form': form})


class AddToGroupView(View):
    def post(self, request, id):
        action = request.POST.get("action")
        person = Person.objects.get(pk=id)
        if action == "Create":
            form = GroupForm(data=request.POST)
            if form.is_valid():

app/contacts/templates/contacts/address.html
{% extends "contact_layout.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

  <div class="content-section">
    <div class="media">
      <div class="container">
        <div class="media-body">
          <h2 class="account-heading">Address</h2>
        </div>
      </div>
    </div>
    <hr>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-primary" type="submit" name="submit" value="Submit">
    </form>
  </div>

{% endblock content %}

app/contacts/templates/contacts/contact_details.html
{% extends "contact_layout.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}
{% if contact %}

    <div class="row">
      <div class="col-lg-7">

        <div class="list-group">
          <li class="list-group-item">
          <div class="container">
            <div class="content-section">
              <div class="media">
                <img class="rounded-circle account-img" src="{{ contact.photo.url }}" alt="user_img">
                <div class="container">
                  <div class="media-body">
                    <h2 class="account-heading">{{ contact.name }} {{ contact.surname }}</h2>
                  </div>
                </div>
              </div>
              <hr>
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-outline-primary btn-sm" type="submit" name="submit" value="Update">
              </form>
            </div>
          </div>
          </li>
        </div>

      </div>

      <div class="col-lg-5">
          <div class="content-section">
            <form method="post" action="{% url 'contacts:add-to-group' id=contact.id %}">
              {% csrf_token %}
              {{ group_form|crispy }}
              <input class="btn btn-primary" type="submit" name="action" value="Create">
            </form>
          </div>
          <br>

          <div class="content-section">
            <form method="post" action="{% url 'contacts:add-to-group' id=contact.id %}">
              <input type="hidden" name="id" value="{{ contact.id }}">
              {% csrf_token %}
              {{ join_group_form|crispy }}
              <input class="btn btn-primary" type="submit" name="action" value="Join">
            </form>
          </div>
          <hr>

        <div class="row">
          {% if person_groups %}
          <div class="container">
          <h5>Groups joined</h5>
            <ul>
              {% for g in person_groups %}
                <li>
                  <form method="post" style="display:inline!important;" action="{% url 'contacts:remove-from-group' %}">{% csrf_token %}
                    <input type="hidden" name="id" value="{{ g.id }}">
                    <input type="hidden" name="person_id" value="{{ contact.id }}">
                    <button class="btn btn-link" name="action" value="delete" type="submit">[x]</button>
                  </form>
                  <a href="{% url 'contacts:group' id=g.id %}">{{ g.name }}</a>
                </li>
              {% endfor %}
            </ul>
          <hr>
          </div>
          {% endif %}
        </div>

        <div class="row">
          {% if phones %}
          <div class="container">
          <h5>Phones</h5>
            <ul>
              {% for p in phones %}
                <li>
                  <form method="post" style="display:inline!important;">{% csrf_token %}
                    <input type="hidden" name="id" value="{{ p.id }}">
                    <button class="btn btn-link" name="action" value="delete_phone" type="submit">[x]</button>
                  </form>
                  <a href="{% url 'contacts:modify-phone' id=contact.id phone_id=p.id %}">[edit] </a>{{ p.number }} | {{ p.get_number_type_display }}
                </li>
              {% endfor %}
            </ul>
          <hr>
          </div>
          {% endif %}
        </div>

        <div class="row">
          {% if emails %}
          <div class="container">
          <h5>Emails</h5>
          <ul>
            {% for e in emails %}
              <li>
                <form method="post" style="display:inline!important;">{% csrf_token %}
                  <input type="hidden" name="id" value="{{ e.id }}">
                  <button class="btn btn-link" name="action" value="delete_email" type="submit">[x]</button>
                </form>
                <a href="{% url 'contacts:modify-email' id=contact.id email_id=e.id %}">[edit] </a>{{ e.email }} | {{ e.get_email_type_display }}
              </li>
            {% endfor %}
          </ul>
          <hr>
          </div>
          {% endif %}
        </div>

        <div class="row">
          {% if addresses %}
          <div class="container">
          <h5>Adressess</h5>
          <ul>
            {% for a in addresses %}
              <li>
                <form method="post" style="display:inline!important;">{% csrf_token %}
                  <input type="hidden" name="id" value="{{ a.id }}">
                  <button class="btn btn-link" name="action" value="delete_address" type="submit">[x]</button>
                </form>
                <a href="{% url 'contacts:modify-address' id=contact.id address_id=a.id %}">[edit] </a>{{ a.city }} {{ a.zip_code }}, {{ a.street }} {{ a.home_no }}/{{ a.apartment_no }}
              </li>
            {% endfor %}
          </ul>
          <hr>
          </div>
          {% endif %}
        </div>

      </div>
    </div>

{% endif %}
{% endblock content %}

app/contacts/templates/contacts/contact_list.html
{% extends "contact_layout.html" %}
{% block content %}
{% load crispy_forms_tags %}

  <div class="row">
    <div class="col-sm">
      <div class="list-group">
        <li class="list-group-item bg-dark text-light"><strong>Contacts</strong></li>
        {% for contact in contacts %}
          <a class="list-group-item list-group-item-action" href="{% url 'contacts:contact' id=contact.id %}">{{contact.full_name}}</a>
        {% endfor %}
      </div>
    </div>

    <div class="col-sm">
      <div class="content-section">
        <div class="media">
          <div class="container">
            <div class="media-body">
              <h2 class="account-heading">New Contact</h2>
            </div>
          </div>
        </div>
        <hr>
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <input class="btn btn-primary" type="submit" name="submit" value="Create">
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

app/contacts/templates/contacts/email.html
{% extends "contact_layout.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

  <div class="content-section">
    <div class="media">
      <div class="container">
        <div class="media-body">
          <h2 class="account-heading">Email</h2>
        </div>
      </div>
    </div>
    <hr>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-primary" type="submit" name="submit" value="Submit">
    </form>
  </div>

{% endblock content %}

app/contacts/templates/contacts/group.html
{% extends "contact_layout.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

  <div class="content-section">
    <div class="media">
      <div class="container">
        <div class="media-body">
          <h2 class="account-heading">Group</h2>
        </div>
      </div>
    </div>
    <hr>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-primary" type="submit" name="submit" value="Submit">
    </form>
  </div>

{% endblock content %}

app/contacts/templates/contacts/group_details.html
{% extends "contact_layout.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container">
<h5>{{ group.name }} - contacts</h5>
  <ul>
    {% for contact in contacts %}
      <li>
        <a href="{% url 'contacts:contact' id=contact.id %}">{{ contact.full_name }}</a>
      </li>
    {% endfor %}
  </ul>
<hr>
</div>

{% endblock content %}

app/contacts/templates/contacts/groups.html
{% extends "contact_layout.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

{% if groups %}
<div class="container">
<h5>Groups</h5>
  <ul>
    {% for g in groups %}
      <li>
        <form method="post" style="display:inline!important;">{% csrf_token %}
          <input type="hidden" name="id" value="{{ g.id }}">
          <button class="btn btn-link" name="action" value="delete" type="submit">[x]</button>
        </form>
        <a href="{% url 'contacts:modify-group' group_id=g.id %}">[edit] </a>
        <a href="{% url 'contacts:group' id=g.id %}">{{ g.name }}</a>
      </li>
    {% endfor %}
  </ul>
<hr>
</div>
{% endif %}

{% endblock content %}

app/contacts/templates/contacts/phone.html
{% extends "contact_layout.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

  <div class="content-section">
    <div class="media">
      <div class="container">
        <div class="media-body">
          <h2 class="account-heading">Phone</h2>
        </div>
      </div>
    </div>
    <hr>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-primary" type="submit" name="submit" value="Submit">
    </form>
  </div>

{% endblock content %}

app/contacts/templates/contacts/search.html
{% extends "contact_layout.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

{% if contacts %}
<div class="container">
<h5>Contacts found</h5>
  <ul>
    {% for contact in contacts %}
      <li>
        <a href="{% url 'contacts:contact' id=contact.id %}">{{ contact.full_name }}</a>
      </li>
    {% endfor %}
  </ul>
<hr>
</div>
{% endif %}

{% endblock content %}